name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        shell: bash
        run: |
          WORKSPACE=/github/workspace/ros2_ws
          mkdir -p $WORKSPACE/src
          rsync -av ./ $WORKSPACE/src/workpkg/
          cd $WORKSPACE

          . /opt/ros/humble/setup.bash

          colcon build --symlink-install
          . install/setup.bash

          ./src/workpkg/test/test.bash



