name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: |
          WORKSPACE=/github/workspace/ros2_ws
          mkdir -p $WORKSPACE/src
          rsync -av ./ $WORKSPACE/src/workpkg/
          cd $WORKSPACE
          source /opt/ros/humble/setup.bash
          export ROS_LOG_DIR=$WORKSPACE/log
          mkdir -p $ROS_LOG_DIR
          colcon build --symlink-install
          source install/setup.bash
          chmod +x ./src/workpkg/test/test.bash
          ./src/workpkg/test/test.bash


